# Generated by Django 5.2.5 on 2025-09-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_city_visit_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='city_name',
        ),
    ]
